name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './code/manufacturing-sim/package-lock.json'
        
    - name: Install dependencies without cache
      run: npm ci
      working-directory: ./code/manufacturing-sim

    - name: Linting
      run: npm run lint:fix
      working-directory: ./code/manufacturing-sim

    - name: Building
      run: npm run build
      working-directory: ./code/manufacturing-sim

    - name: Tests
      run: npm run test:coverage
      working-directory: ./code/manufacturing-sim
      
